CREATE DATABASE rei_da_garapa;
USE rei_da_garapa;

CREATE TABLE Users (
    ID INTEGER PRIMARY KEY AUTO_INCREMENT,
    Name VARCHAR(150) NOT NULL,
    Email VARCHAR(150) UNIQUE NOT NULL,
    Password VARCHAR(150) NOT NULL
);

CREATE TABLE Products (
    ID INTEGER PRIMARY KEY AUTO_INCREMENT,
    Name VARCHAR(150) NOT NULL,
    Quantity INTEGER NOT NULL,
    Price double(6,2) NOT NULL,
    Image VARCHAR(1000) NOT NULL,
    Description VARCHAR(250)
);

CREATE TABLE Sales (
    Sale_ID INTEGER PRIMARY KEY AUTO_INCREMENT,
    Product_ID INTEGER NOT NULL,
    Sale_Time DATETIME DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (Product_ID) REFERENCES Products(ID)
);